# This is a config for E2B sandbox template.
# You can use template ID (txi0c1g2neci34re70eq) or template name (stu-vibe-nextjs-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("stu-vibe-nextjs-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("stu-vibe-nextjs-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('stu-vibe-nextjs-test-2')

team_id = "468e8fdf-260f-40e9-be2a-eeefef9ce423"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "stu-vibe-nextjs-test-2"
template_id = "txi0c1g2neci34re70eq"
